### ISSUE TITLE
Ellipsis at end of thread stacks

### ISSUE THREAD

**Issue by bostrt** [engineersamuel/javahighcpu#7]
The entire thread stack is not printed out if the stack is deeper than ~8. It would be nice if there were ellipsis (or something else) to indicate this. Example of what I am seeing is below:

```
Read 5 top outputs and 5 thread dumps.
Found offending processes @ Mon Jun 22 2015 13:09:50 GMT-0400 (EDT)
    pid: 27050  hex: 0x69aa cpu: 35.0%  mem: 47.6%
    "ajp-0.0.0.0-8009-8" daemon prio=10 tid=0x00007f54f00a2800 nid=0x69aa runnable [0x00007f540ab68000]
    java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:129)
    at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1525)
    at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:3267)
    - locked <0x00000005ed48c180> (a com.microsoft.sqlserver.jdbc.TDSReader)
    at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:4422)
    at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:386)
    at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:338)
    at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:4016)
```

**Comment by bostrt** [comment]
NVM, I found out there is a `-l` flag.

**Comment by engineersamuel** [comment]
I think this is still a valid concern.  I will add a ... (pass -l <num> to increase from the default 10 if desired)
